import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import SiteHeader from "@/components/site-header";

export default async function DrawsPage() {
  const supabase = createClient();
  const { data: draws } = await supabase.from("draws").select("id,month,draw_type,winning_numbers,jackpot_rollover_amount,published_at").eq("status", "published").order("month", { ascending: false });
  const latest = draws?.[0];
  return <main><SiteHeader /><section className="page-wrap">
    <div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-end">
      <div><p className="eyebrow">Monthly draw archive</p><h1 className="mt-3 font-display text-5xl leading-tight sm:text-6xl">The results are public. The mechanics stay clear.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-ink/60">Every published draw records the five winning numbers, draw logic, and any five-match jackpot rollover.</p></div>
      <div className="panel-muted p-6"><p className="metric-label">How prizes work</p><div className="mt-4 grid grid-cols-3 gap-3 text-center">{[["40%","5-match"],["35%","4-match"],["25%","3-match"]].map(([pct,label])=><div key={label}><p className="font-display text-2xl">{pct}</p><p className="mt-1 text-[10px] text-ink/45">{label}</p></div>)}</div></div>
    </div>
    {!draws?.length ? <div className="panel mt-10 p-12 text-center"><span className="grid mx-auto h-12 w-12 place-items-center rounded-full bg-fairway/8 text-fairway">◎</span><p className="mt-5 font-display text-3xl">First draw coming soon.</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-ink/50">The archive will appear here once an administrator has simulated, reviewed, and published the first monthly draw.</p><Link href="/subscribe" className="btn-primary mt-6">Join the next draw →</Link></div> : <>
      {latest && <article className="mt-10 overflow-hidden rounded-[22px] border border-fairway/10 bg-fairway p-6 text-white shadow-soft sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-white/55">Latest published draw</p><h2 className="mt-2 font-display text-3xl">{new Date(latest.month + "T00:00:00").toLocaleDateString(undefined,{year:"numeric",month:"long"})}</h2><p className="mt-2 text-sm text-white/65">{latest.draw_type === "algorithmic" ? "Algorithmic selection" : "Random selection"}</p></div><div className="flex flex-wrap gap-2">{latest.winning_numbers.map((n:number)=><span key={n} className="grid h-12 w-12 place-items-center rounded-xl bg-white font-mono font-semibold text-fairway">{n}</span>)}</div><div className="rounded-2xl border border-white/15 bg-white/5 p-4"><p className="text-[10px] uppercase tracking-[.14em] text-white/50">5-match rollover</p><p className="mt-2 font-display text-2xl">${Number(latest.jackpot_rollover_amount || 0).toLocaleString()}</p></div></div></article>}
      <div className="mt-7 grid gap-4">{draws.slice(1).map((d)=><article key={d.id} className="panel flex flex-col gap-5 p-5 sm:p-6 md:flex-row md:items-center md:justify-between"><div><p className="eyebrow">{new Date(d.month + "T00:00:00").toLocaleDateString(undefined,{year:"numeric",month:"long"})}</p><h2 className="mt-2 font-display text-2xl">{d.draw_type === "algorithmic" ? "Algorithmic" : "Random"} draw</h2><p className="mt-2 text-xs text-ink/45">Published {d.published_at ? new Date(d.published_at).toLocaleDateString() : "—"}</p></div><div className="flex flex-wrap gap-2">{d.winning_numbers.map((n:number)=><span key={n} className="number-chip">{n}</span>)}</div><div className="md:text-right"><p className="metric-label">Jackpot rollover</p><p className="mt-1 font-display text-2xl">${Number(d.jackpot_rollover_amount || 0).toLocaleString()}</p></div></article>)}</div></>}
  </section></main>;
}
